project:
  type: website

website:
  title: "IS415 GeoSpatial Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projectproposal.qmd
        text: Project Proposal
      - href: ./report/report.qmd
        text: Project Report
      - text: "Project Artifacts"
        menu:
        - href: poster.qmd
          text: Poster    
        - href: userguide.qmd
          text: User Guide
        - href: ./GWRProj/DataPreprocessing.qmd
          text: Date Preprocessing for Shiny Model
        - href: https://is415-hdb2023.shinyapps.io/Shiny_app/
          text: Shiny Application

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

