project:
  type: website

website:
  title: "IS415 GeoSpatial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projectproposal.qmd
        text: Project Proposal

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

