project:
  type: website

website:
  title: "IS415 GeoSpatial"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projectproposal.qmd
        text: Project Proposal
      - href: poster.qmd
        text: Poster        
      - href: report.qmd
        text: Project Report
      - href: userguide.qmd
        text: User Guide
      - href: ./GWRProj/DataPreprocessing.qmd
        text: Date Preprocessing for Shiny Model



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

