---
title: "Prototyping V1"
format: html
editor: visual
---

## Load the packages

```{r}
pacman::p_load(tidyverse, sf, tmap, sfdep, ggplot2, dplyr, lubridate)
```

Load the Singapore Map (NOTES: We only want the PLN_AREA_N)

```{r}
mpsz <- st_read(dsn = "data/geospatial", 
                  layer = "MP14_SUBZONE_WEB_PL")
```

```{r}
st_crs(mpsz)
```

Load all the required files

```{r}
resale_file_2017 <- read.csv("data/aspatial/resale-flat-prices-based-on-registration-date-from-jan-2017-onwards.csv")
```

Look at the data

```{r}
resale_file_2017
```

Append Date Text (We assume all are on the first)

```{r}
resale_file_2017$month <- paste(resale_file_2017$month, "01", sep = "-") 
```

```{r}
resale_file_2017
```

Convert the month column to date type

```{r}
resale_file_2017$month <- as.Date(resale_file_2017$month, format = "%Y-%m-%d")
```

Filter the data to only include 2019 as we only want to see 2019

```{r}
resale_file_2019 <- resale_file_2017 %>% filter(month >= "2019-01-01")
```

```{r}
resale_file_2019
```

Visualize the map:

```{r}
tm_shape(mpsz) + 
  tm_polygons("PLN_AREA_N")
```

Remove outer islands:

```{r}
unique(mpsz$PLN_AREA_N)
```

```{r}
mpsz_no_outer_island <- mpsz %>% 
  filter(!PLN_AREA_N %in% c("WESTERN ISLANDS", "SOUTHERN ISLANDS", "NORTH-EASTERN ISLANDS") )
```

```{r}
tm_shape(mpsz_no_outer_island) +
  tm_polygons("PLN_AREA_N")
```

Compare both sets of data together

```{r}
mpsz_planning_area_list <- c(mpsz_no_outer_island)
```
